apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
type: Opaque
data:
  # Değerleri yine base64 formatında gireceksin
  MailSettings__Username: YmlsYWx0YW5idDA3QGdtYWlsLmNvbQ==
  MailSettings__Password: c2lmcmVuX2J1cmF5YV9nZWxlY2Vr
  MailSettings__From: YmlsYWx0YW5idDA3QGdtYWlsLmNvbQ==